std::string join(const std::vector<std::string>& strings, std::string delim);
std::vector<std::string> split(std::string str, char delimiter);
void RemoveAll(std::string& s, const char& c);
void ReplaceAll(std::string&s, const std::string& before, const std::string& after);
float CalculateString(std::string s);
bool IsOperator(const char& c);
bool IsOperator(const std::string& s);
std::string charToString(const char& c);
float Calculate(const float& a, const std::string& oper, const float& b);
float CalculateString(std::string s);
